version: "3"

services:
  app:
    build:
      context: ./docker/app
    ports:
      - 81:80
    volumes:
      - ./:/var/www/html
      - ./storage/logs/apache:/var/log/apache2:rw
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgresql_data:
